djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from djangocrudAjax import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name="home"),
    
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
    path("comments/",include('comments.urls')),
    path("tutorial/",include('tutorial.urls')),
    path("dropdown/",include('dropdown.urls')),
    path("userDropdown/",include('userDropdown.urls')),

]

# faire marcher les fichier static et media
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskUpdateDeleteView,TutorialDataView, TutorialView #, TutorialDataView, TaskUpdateView

app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskUpdateDeleteView.as_view(), name="updateDelete"), 
    #path('view/<int:pk>', TaskUpdateView.as_view(), name="update"),
    
    path('tutorial', TutorialView.as_view(), name="tutorial"),
    path('tutorial/data', TutorialDataView.as_view(), name="tutorial_data"), 
    
    
]

userDropdown/urls.py
from django.urls import include, path
from . import views

app_name = "userDropdown"

urlpatterns = [
                                                   # pattern-name
    path('', views.StudentListView.as_view(), name='student_changelist'),
    path('add/', views.StudentCreateView.as_view(), name='student_add'),
    path('edit/<int:pk>/', views.StudentUpdateView.as_view(), name='student_change'),
    path('delete/<int:pk>/', views.StudentDeleteView.as_view(), name='student_delete'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),
   ]

userDropdown/models.py
from django.db import models

# Create your models here.
class College(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class Branch(models.Model):
    college = models.ForeignKey(College, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Student(models.Model):
    name = models.CharField(max_length=100)
    birthdate = models.DateField(null=True, blank=True)
    college = models.ForeignKey(College, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name 

userDropdown/forms.py
from django import forms
from .models import Student, Branch

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'birthdate', 'college', 'branch')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'college' in self.data:
            try:
                college_id = int(self.data.get('college'))
                self.fields['branch'].queryset = Branch.objects.filter(college_id=college_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.college.branch_set.order_by('name')

userDropdown/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.http import HttpResponse, JsonResponse
from django import http
from .models import Student, Branch
from .forms import StudentForm
from django.shortcuts import render

class StudentListView(ListView):
    model = Student
    form_class = StudentForm
    context_object_name = 'students'

class StudentCreateView(CreateView):
    model = Student
    form_class = StudentForm
                                  # app-name:pattern-name
    success_url = reverse_lazy('userDropdown:student_changelist')

class StudentUpdateView(UpdateView):
    model = Student
    form_class = StudentForm  
                                  # app-name:pattern-name
    success_url = reverse_lazy('userDropdown:student_changelist')
    
class StudentDeleteView(DeleteView):
    model = Student
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('userDropdown:student_changelist')
    template_name = 'userDropdown/confirm-delete.html'
    

def load_branches(request):
    college_id = request.GET.get('college')
    branches = Branch.objects.filter(college_id=college_id).order_by('name')
    return render(request, 'userDropdown/branch_dropdown_list_options.html', {'branches': branches})

templates/userDropdown/branch_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

templates/userDropdown/confirm-delete.html
{% extends 'layout.html' %}

{% block content %}

<div class="container pt-5">
    <form method="post">
        {% csrf_token %}
        <p>Are you sure , you want to delete "{{ object }} ?</p>
        <input type="submit" value="Confirm">
    </form>
</div>
{% endblock content%}

templates/userDropdown/student_form.html
{% extends 'layout2.html' %}

{% block content %}

  <h2>Student Form</h2>

  <form method="post" id="studentForm" data-branches-url="{% url 'userDropdown:ajax_load_branches' %}" novalidate>
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
    <a href="{% url 'userDropdown:student_changelist' %}">Nevermind</a>
  </form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
    $("#id_college").change(function(){
      var url = $("#studentForm").attr("data-branches-url");  
      var collegeId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'college': collegeId       
        },
        success: function (data) {  
          $("#id_branch").html(data);  
        }
      });

    });
  </script>


{% endblock %}

templates/userDropdown/student_list.html
{% extends 'layout2.html' %}

{% block title %}Human Resources Module{% endblock %}

<!--block content-->
{% block content %}
  <h2>Human Resources Module » People Management</h2>

  <p>
    <a href="{% url 'userDropdown:student_add' %}">Add Student</a>
  </p>

  <table border="1">
    <thead>
      <tr>
        <th>Name</th>
        <th>Birthdate</th>
        <th>College</th>
        <th>Branch</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
        <tr class="record">
          <td><a href="{% url 'userDropdown:student_change' student.pk %}">{{ student.name }}</a></td>
          <td>{{ student.birthdate }}</td>
          <td>{{ student.college.name }}</td>
          <td>{{ student.branch.name }}</td>
          <td>
                            <!--'app_name:pattern_name'-->
            <a href="{% url 'userDropdown:student_delete' student.pk  %}" class="link-delete text-danger">Delete</a>
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No person in the database. <a href="{% url 'userDropdown:student_add' %}">Add the first person</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock content%}