djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from djangocrudAjax import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name="home"),
    
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
    path("comments/",include('comments.urls')),
    path("tutorial/",include('tutorial.urls')),
    path("dropdown/",include('dropdown.urls')),
    path("userDropdown/",include('userDropdown.urls')),

]

# faire marcher les fichier static et media
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import ProductView, ProductCategoryView, FormRegisterView

app_name = "products"

urlpatterns = [
    path('', ProductView.as_view(), name="products"), 
    path('register', FormRegisterView.as_view(), name="register"),
    path('<str:category>', ProductCategoryView.as_view(), name="products_category"), 
]

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskUpdateDeleteView,TutorialDataView, TutorialView #, TutorialDataView, TaskUpdateView

app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskUpdateDeleteView.as_view(), name="updateDelete"), 
    #path('view/<int:pk>', TaskUpdateView.as_view(), name="update"),
    
    path('tutorial', TutorialView.as_view(), name="tutorial"),
    path('tutorial/data', TutorialDataView.as_view(), name="tutorial_data"), 
    
    
]

userDropdown/urls.py
from django.urls import include, path
from . import views

app_name = "userDropdown"

urlpatterns = [
                                                   # pattern-name
    path('', views.StudentListView.as_view(), name='student_changelist'),
    path('add/', views.StudentCreateView.as_view(), name='student_add'),
    path('edit/<int:pk>/', views.StudentUpdateView.as_view(), name='student_change'),
    path('delete/<int:pk>/', views.StudentDeleteView.as_view(), name='student_delete'),
    path('ajax/load-branches/', views.load_branches, name='ajax_load_branches'),
   ]

products/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(null=True, blank=True, max_length = 150)
    category = models.CharField(null=True, blank=True, max_length=50)
    image = models.ImageField(null=True, blank=True, upload_to="products")
    created_at = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    def __str__(self):
        return f"{self.name}"

products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
        
    class Meta:
        model = Product
        fields = ["name", "category", "image"]

products/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.template import loader
from products.models import Product



class ProductView(View):
    def get(self,request, *args, **kwargs):
        products = Product.objects.values('category').distinct()
        context = {
            "product_list": products
        }
        return render(request, "products/index.html", context)
    

class ProductCategoryView(View):
    def get(self,request, category, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
            products = Product.objects.filter(category=category)
            context = {
                "product_image_list": products
            }
            template = loader.get_template("products/category.html")
            return HttpResponse(template.render(context, self.request))
        return HttpResponse("Wrong request")
    
    
class FormRegisterView(View):
    def post(self,request, *args, **kwargs):
        tuto = Product(name=request.POST.get('name'), category=request.POST.get('category'), image=request.POST.get('file'), created_at=request.POST.get('created_at'), updated_at=request.POST.get('updated_at'))
        tuto.save()
        return redirect('/')
    
    def get(self, request, *args, **kwargs):
        return render(request, "products/formulaire.html", {})

    

templates/products/category.html
<div class="row">
    {% for product in product_image_list %}
    <div class="col-sm-4">
        <img src="{{product.image.url}}" alt="image" width="200" height="200" class="img-responsive">
    </div>
    {% endfor %}
</div>

templates/products/formulaire.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3 ">
            
            <form id="formProd"  action="{% url 'products:register'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row ">
                    <div class="col-12">
                        <div class="form-group validate">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="form-group validate">
                            <label for="category">Category</label>
                            <input type="text" name="category" class="form-control" id="category" placeholder="Enter category">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="form-group validate">
                            <label for="image">Image</label>
                            <input type="file" name="file" class="form-control image-value" id="id_image">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>


                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="created_at">Created_at</label>
                            <input type="time" name="created_at" class="form-control" id="created_at">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>


                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="updated_at">Updated_at</label>
                            <input type="time" name="updated_at" class="form-control" id="updated_at">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>

                    <div class="col-12 ">
                        <button type="submit" id="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                            {% comment %} {% url 'app-name:name' %} {% endcomment %}
                        <a class="" href="{% url 'products:products'  %}">Voir produit</a>
                    </div>

                    

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>

// Poster dans la base de données 
$(document).ready(function(){
    $('#submit').on('click', function(e){
        e.preventDefault();
        e.stopPropagation();
        alert("bonjour")
        $url = $('#formProd').attr('action');
        var img_data = $('#id_image').get(0).files[0];

        let formdata = new FormData();
        formdata.append('name', $('[name=name]').val());
        formdata.append('category', $('[name=category]').val());
        formdata.append('created_at', $('[name=created_at]').val());
        formdata.append('updated_at', $('[name=updated_at]').val());
        formdata.append("img_data", img_data);
        $.ajax({
            type: "POST",
            url: $url, // 
            headers:{ 'X-CSRFToken': '{{ csrf_token }}'},
            data: formdata,
            cache: false,
            processData: false,
            contentType:false,
            success: function(){
                alert('Save Data');
                $('#name').val('');
                $('#category').val('');
                $('#id_image').val('');
                $('#created_at').val('');
                $('#updated_at').val('');
                //window.location = "/";
            
            }
            
            })

    
    
    })
    
})

</script>
{% endblock scripts %}

templates/products/index.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3">

            <!---->
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                {% for product in product_list %}
                <!---->
                <li class="nav-item" role="presentation">
                    <a class="nav-link {% if forloop.counter == 1 %} active {% endif %} category-link" id="{{product.category}}-tab" data-url="{% url 'products:products_category' product.category  %}" data-toggle="tab" href="#{{product.category}}" role="tab" aria-controls="home" aria-selected="true">{{product.category|upper}}</a>
                </li>
                {% endfor %}
                
                <!-- <li class="nav-item" role="presentation">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Category</a>
                </li>
                <li class="nav-item" role="presentation">
                  <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Category</a>
                </li> -->
            </ul>
            
            <!---->
            <!--image-->
            <div class="tab-content" id="myTabContent">
                <div class="mt-4 imageContent">

                </div>
                
            </div>
            <br>
            <div class="col-6">
                <a href="{% url 'products:register' %}">formulaire</a>
                
            </div>
            

            
        </div>
    </div>
</div>  
{% endblock content %}

{% block scripts %}
<script>
    function getFirstCategoryImages()
    {
        let url  = $(".category-link:first").data('url');
        $.ajax({
            url: url,
            type: "GET",
            success: function(resp){
                $(".imageContent").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }

    getFirstCategoryImages();

    $(".category-link").on("click", function(){
        var $this = $(this);
        $.ajax({
            url: $this.data('url'),
            type: "GET",
            success: function(resp){
                $(".imageContent").html(resp);
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
        return false;
    });
</script>
{% endblock scripts %}