comments/urls.py
from django.urls import path
from .views import CommentView, CommentDataView

app_name = "comments"

urlpatterns = [
    path('', CommentView.as_view(), name="comment"), 
    path('/view', CommentDataView.as_view(), name="comment_data"), 
]

djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from djangocrudAjax import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name="home"),
    
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
    path("comments/",include('comments.urls')),
    path("tutorial/",include('tutorial.urls')),
    path("dropdown/",include('dropdown.urls')),
    path("userDropdown/",include('userDropdown.urls')),

]

# faire marcher les fichier static et media
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dropdown/urls.py
from django.urls import path
from .views import index, load_courses, insert

app_name = "dropdown"

urlpatterns = [
    path('', index, name="index"), 
    path('insert/', insert, name='insert'),
    path('load-courses/', load_courses, name='ajax_load_courses'),
]

products/urls.py
from django.urls import path
from products.views import ProductView, ProductCategoryView, FormRegisterView

app_name = "products"

urlpatterns = [
    path('', ProductView.as_view(), name="products"), 
    path('register', FormRegisterView.as_view(), name="register"),
    path('<str:category>', ProductCategoryView.as_view(), name="products_category"), 
]

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskUpdateDeleteView,TutorialDataView, TutorialView #, TutorialDataView, TaskUpdateView

app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskUpdateDeleteView.as_view(), name="updateDelete"), 
    #path('view/<int:pk>', TaskUpdateView.as_view(), name="update"),
    
    path('tutorial', TutorialView.as_view(), name="tutorial"),
    path('tutorial/data', TutorialDataView.as_view(), name="tutorial_data"), 
    
    
]

tutorial/urls.py
from django.urls import path
from tutorial.views import TutorialView, GetProductView

app_name = "tutorial"

urlpatterns = [
    path('', TutorialView.as_view(), name="index"), 
    path('<str:category>', GetProductView.as_view(), name="category"), 
]

templates/home.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="col-2" >
         {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
       <a href="{% url 'tasks:task' %}" class="link-danger">Tasks</a> 
    </div>
    <div class="col-2" >
        {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
      <a href="{% url 'products:products' %}" class="link-danger">Products</a> 
    </div>
    <div class="col-2" >
      {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
      <a href="{% url 'comments:comment' %}" class="link-danger">Comments</a> 
    </div>

    <div class="col-2" >
      {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
      <a href="{% url 'tasks:tutorial' %}" class="link-danger">tutorial</a> 
    </div>
    <div class="col-2" >
      {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
      <a href="{% url 'tutorial:index' %}" class="link-danger">tutorial select</a> 
    </div>
    <div class="col-2" >
      {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
      <a href="{% url 'dropdown:index' %}" class="link-danger">dropdown</a> 
    </div>
    <div class="col-2" >
      {% comment %} <!-- {% url 'app-name:name' %} --> {% endcomment %}
      <a href="{% url 'userDropdown:student_changelist' %}" class="link-danger">userDropdown</a> 
    </div>
    
</div>

{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Tasky</title>
  {% load static %}

  <!--boostrap-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  

  <!-- custom css & js -->
  <script src={% static 'main.js' %} defer></script>
  <script src={% static 'semantic.js' %} defer></script>
  <link rel="stylesheet" href={% static "style.css" %}>

  <!--jQuery-->
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

  <!-- semantic UI -->
  <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css" integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.js" integrity="sha512-Xo0Jh8MsOn72LGV8kU5LsclG7SUzJsWGhXbWcYs2MAmChkQzwiW/yTQwdJ8w6UA9C6EVG18GHb/TrYpYCjyAQw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  {% block styles %}
  {% endblock styles %}
</head>

<body class="body-content">

    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
        <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto ml-5">
            
            <!-- <li class="nav-item active">
              <a class="nav-link" href="{% url 'tasks:task'  %}">Add Task <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tasks:view'  %}">View Task</a>
            </li> -->
          </ul>
        </div>
      </nav>

  <!-- Content Wrapper. Contains page content -->
  

  <div class="ui container mt-5">
    {% block content %}
    {% endblock content %}
  </div>
  <!-- /.content-wrapper -->


  <!-- cdn jQuery-->
  <!--js-->
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
  <!--boostrap js-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>
</html>

templates/layout2.html
{% load static %}
<!doctype html>
<meta charset="utf-8">
    <title>{% block title %}Student Database{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tasky</title>
    {% load static %}

    <!--jQuery-->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    
  </head>
  <body>
    <h1>Student Database</h1>
    <hr>
    {% block content %}
    {% endblock %}

     <!-- cdn jQuery-->
      <!--js-->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>