djangocrudAjax/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from djangocrudAjax import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name="home"),
    
    path("tasks/",include('tasks.urls')),
    path("products/",include('products.urls')),
    path("comments/",include('comments.urls')),
    path("tutorial/",include('tutorial.urls')),
    path("dropdown/",include('dropdown.urls')),
    path("userDropdown/",include('userDropdown.urls')),

]

# faire marcher les fichier static et media
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path
from .views import TaskView, ViewTaskView, TaskUpdateDeleteView,TutorialDataView, TutorialView #, TutorialDataView, TaskUpdateView

app_name = "tasks"

urlpatterns = [
    path('', TaskView.as_view(), name="task"), 
    path('view', ViewTaskView.as_view(), name="view"), 
    path('view/<int:pk>', TaskUpdateDeleteView.as_view(), name="updateDelete"), 
    #path('view/<int:pk>', TaskUpdateView.as_view(), name="update"),
    
    path('tutorial', TutorialView.as_view(), name="tutorial"),
    path('tutorial/data', TutorialDataView.as_view(), name="tutorial_data"), 
    
    
]

tutorial/urls.py
from django.urls import path
from tutorial.views import TutorialView, GetProductView

app_name = "tutorial"

urlpatterns = [
    path('', TutorialView.as_view(), name="index"), 
    path('<str:category>', GetProductView.as_view(), name="category"), 
]

tasks/models.py
from django.db import models

class Task(models.Model):
    owner = models.CharField(max_length = 150)
    name = models.CharField(max_length = 150)
    task_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.name}"
    
    
    
    

tutorial/models.py
from django.db import models

class Tuto(models.Model):
    product = models.CharField(null=True, blank=True, max_length=150 )
    category = models.CharField(null=True, blank=True, max_length=50)
    
    def __str__(self):
        return f"{self.category}"
    
    

tasks/forms.py
from django import forms
from tasks.models import Task

class TaskForm(forms.ModelForm):
        
    class Meta:
        model = Task
        fields = ["owner", "name", "task_date", "start_time", "end_time"]

tutorial/forms.py
from django import forms

tasks/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from tasks.forms import TaskForm
from tasks.models import Task
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.template import loader
import json
# from django.shortcuts import render, redirect
# from django.template import loader


# poster les données dans la base de donnée
class TaskView(View):
    # apres validation de la methode ajax (voir si formulaire correcte )
    
    #alors
    form_class = TaskForm
    def post(self, request, *args, **kwargs):
        # si mrethode ajax est validé avec succès
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
            # alors recupere le formulaire avec les données
            form = self.form_class(request.POST)
            # si formulaire valide
            if form.is_valid():
                # save dans la base de données
                form.save()
                return JsonResponse({"message": "success"}) # success voir ajax
            return JsonResponse({"message": "Validation failed"})
        return JsonResponse({"message": "Wrong request"})

    def get(self,request, *args, **kwargs):
        return render(request, "tasks/index.html", {})


class ViewTaskView(View):
    def get(self,request, *args, **kwargs):
        tasks = Task.objects.all()
        return render(request, "tasks/view.html", {"tasks":tasks})



class TaskUpdateDeleteView(View):
    
    # get pour recuperation et supprimer 
    def get(self,request, pk, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
            task = Task.objects.get(pk=pk)
            print(task)
            task.delete()
            return JsonResponse({"message":"success"})
        return JsonResponse({"message": "Wrong request"})
    
    # poster pour Update
    form_class = TaskForm
    def post(self, request, pk, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
            task = Task.objects.get(pk=pk)
            
            # dictionnaire pour transferer dans les pages HTML
            data = {
                "owner":task.owner, 
                "name":task.name, 
                "task_date":task.task_date, 
                "start_time":task.start_time, 
                "end_time":task.end_time
            }
            form = self.form_class(request.POST, initial=data)
            if form.is_valid():
                #(1) affecter a des variables les données recupéré par
                # chaque entrée du formulaire 
                owner = form.cleaned_data['owner']
                name = form.cleaned_data['name']
                task_date = form.cleaned_data['task_date']
                start_time = form.cleaned_data['start_time']
                end_time = form.cleaned_data['end_time']
                
                #(2) si les données du form a changer
                if form.has_changed():
                    # les nouvelle valeurs sont reafectés
                    task.owner = owner
                    task.name = name
                    task.task_date = task_date
                    task.start_time = start_time
                    task.end_time = end_time
                    task.save()
                    return JsonResponse({'message':'success'})
                return JsonResponse({'message': 'Data is not editted'})
            
            return JsonResponse({'message': 'Validation failed'})
        
        return JsonResponse({'message': 'wrong request'})
    
# class TaskUpdateView(View):
#     form_class = TaskForm
    
#     def post(self, request, pk, *args, **kwargs):
#         if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
#             task = Task.objects.get(pk=pk)
#             data = {
#                 "owner":task.owner, 
#                 "name":task.name, 
#                 "task_date":task.task_date, 
#                 "start_time":task.start_time, 
#                 "end_time":task.end_time
#             }
#             form = self.form_class(request.POST, initial=data)
#             if form.is_valid():
#                 owner = form.cleaned_data['owner']
#                 name = form.cleaned_data['name']
#                 task_date = form.cleaned_data['task_date']
#                 start_time = form.cleaned_data['start_time']
#                 end_time = form.cleaned_data['end_time']
                
#                 if form.has_changed():
#                     task.owner = owner
#                     task.name = name
#                     task.task_date = task_date
#                     task.start_time = start_time
#                     task.end_time = end_time
#                     task.save()
#                     return JsonResponse({'message':'success'})
#                 return JsonResponse({'message': 'Data is not editted'})
            
#             return JsonResponse({'message': 'Validation failed'})
        
#         return JsonResponse({'message': 'wrong request'})
                
class TutorialView(View):
    def get(self,request, *args, **kwargs):
            # tasks = Task.objects.all()
            # # seralise les donnée 
            # task_serializers = serializers.serialize('json', tasks)
            # # convertir en objet Json
            # task_json = json.loads(task_serializers)
            # context = {'task_json': task_json}
            # print(task_json)
            # return render(request, "tasks/tutorial.html", context)
            return render(request, "tasks/tutorial.html")
    
    
class TutorialDataView(View):
    def get(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
            tasks = Task.objects.all()
            # seralise les donnée
            task_serializers = serializers.serialize('json', tasks)
            # convertir en objet Json
            task_json = json.loads(task_serializers)
            return JsonResponse(task_json, safe=False)
        return JsonResponse({'message':'wrong validation'})
    


    
    
            

tutorial/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views import View
from django.shortcuts import render, redirect
from django.template import loader
from products.models import Product
from tutorial.models import Tuto



class TutorialView(View):
    def post(self,request, *args, **kwargs):
        tuto = Tuto(product=request.POST.get('product'), category=request.POST.get('category'))
        tuto.save()
        return redirect('/')
            
    def get(self,request, *args, **kwargs):
        products = Product.objects.values('category').distinct()
        context = {
            "product_list": products
        }
        return render(request, "tutorial/index.html", context)
    
# charger les produits dependant de category
class GetProductView(View):
    def get(self,request, category, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest': # au lieu de is_ajax()
            products = Product.objects.filter(category=category).values('id', 'name')
            return JsonResponse({'data': list(products)})
        return HttpResponse('Wrong request')
    
    

 
    

templates/tasks/index.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-6 offset-3 ">
            
            <form id="formTask"  action="{% url 'tasks:task'  %}" autocomplete="off">
                {% csrf_token %}
                <div class="row ">
                    <div class="col-12">
                        <div class="form-group validate">
                            <label for="owner">Owner</label>
                            <input type="text" name="owner" class="form-control" id="owner" placeholder="Enter owner name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="form-group validate">
                            <label for="name">Task name</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter task name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="form-group validate">
                            <label for="task_date">Task date</label>
                            <input type="date" name="task_date" class="form-control" id="task_date">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>


                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="start_time">Start time</label>
                            <input type="time" name="start_time" class="form-control" id="start_time">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>


                    <div class="col-6">
                        <div class="form-group validate">
                            <label for="end_time">End time</label>
                            <input type="time" name="end_time" class="form-control" id="end_time">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    </div>

                    <div class="col-12 ">
                        <button type="submit" class="btn btn-primary pl-5 pr-5 btnSave">Save</button>
                            {% comment %} {% url 'app-name:name' %} {% endcomment %}
                        <a class="" href="{% url 'tasks:view'  %}">Voir user</a>
                    </div>

                    

                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script>

    // poster les donnée dans la base de données 
    $("#formTask").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this); // this => #formTask
        var valid = true; // booleen 

        // pour chaque input 
        $('#formTask input').each(function() {
            let $this = $(this);
            
            // si un input ne contient pas de valeur 
            if(!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' ')+' field is required');
            }
        });
        
        // si valide 
        if(valid){
            $(".btnSave").text('Saving....').attr('disabled',true);
            let data = $this.serialize(); // regrouper les données émises par le formulaire
            console.log(data)
            $.ajax({
                url: $this.attr("action"), 
                type: "POST",
                data: data,
                dataType: "json",
                success: function(resp){
                    if(resp.message == "success"){
                        alert("Saved successful");
                        $("#formTask")[0].reset();
                    }
                    else{
                        alert(resp.message);
                    }
                    $(".btnSave").text('Save').attr('disabled',false);
                },
                error: function(resp){
                    console.log("Something went wrong");
                    $(".btnSave").text('Save').attr('disabled',false);
                }
                
            });
            
        }
        return false;
    });
</script>
{% endblock scripts %}

templates/tasks/tutorial.html
{% extends 'layout.html' %}

{% block styles %}
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-12 text-center">
            <button class="btn btn-primary btn-get-data">Récupérer le fichier HTML dans un div</button>
                                                    <!--recuper les donnee en json (voir urls.py puis views.py)-->
            <div class="content-data mt-4" data-url="{% url 'tasks:tutorial_data' %}">Le contenu du fichier s'affichera ici </div>
            {% comment %} <div class="content-data mt-4">
                {{ task_json.0.fields.owner }}

            </div> {% endcomment %}
            
        </div>
    </div>
</div>



{% endblock content %}

{% block scripts %}
<script>
    // script pour recuper les donnée en Json
    $(".btn-get-data").on("click", function(){
        $.ajax({
            url: $(".content-data").data('url'),
            type: "GET",
            dataType: 'json',
            success: function(resp){
                //on replace le contenu du div content-data par les données json
                $(".content-data").html("j'ai "+resp[0].pk+" ans");
            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    });

    
</script>
{% endblock scripts %}

templates/tasks/view.html
{% extends 'layout.html' %}

{% block styles %}
<style>
    .text-red{
        color: tomato !important;
    }
</style>
{% endblock styles %}

{% block content %}
<div class="container">
    <div class="row pt-5">
        <div class="col-12 ">
            <table class="table" id="table">
                <thead>
                  <tr>
                    <th scope="col">Owner</th>
                    <th scope="col">Task</th>
                    <th scope="col">Date</th>
                    <th scope="col">Start</th>
                    <th scope="col">End</th>
                    <th scope="col">Actions</th>
                  </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                    <tr class="record">
                        <td>{{ task.owner }}</td>
                        <td>{{ task.name }}</td>
                        <td>{{ task.task_date }}</td>
                        <td>{{ task.start_time }}</td>
                        <td>{{ task.end_time }}</td>
                        <td>
                                        <!--'app_name:name'-->
                            <a href="{% url 'tasks:updateDelete' task.id  %}" data-date="{{ task.task_date|date:"Y-m-d"}}" data-start="{{ task.start_time|date:"H:i"}}" data-end="{{ task.end_time|date:"H:i"}}" class="link-edit mr-2 text-primary">Edit</a>
                            <a href="{% url 'tasks:updateDelete' task.id  %}" class="link-delete text-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
    </div>
</div>

<div class="modal fade" id="editModal" tabindex="-1" arial-labelledby="editModalLabel" aria-hidden="true"> 
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"> 
                    <span aria-hidden="true">&times;</span>
                </button>        
            </div>
            <form id="formEdit"  action="">
                {% csrf_token %}
                <div class="modal-body row g-4">
                        <div class="form-group validate">
                            
                            <input type="text" name="owner" class="form-control" id="owner" placeholder="Enter owner name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="form-group validate">
                           
                            <input type="text" name="name" class="form-control" id="name" placeholder="Enter task name">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="form-group validate">
                            
                            <input type="date" name="task_date" class="form-control" id="task_date">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                    
                        <div class="form-group validate">
                          
                            <input type="time" name="start_time" class="form-control" id="start_time">
                            <small class="text-red text-muted mySpan"></small>
                        </div>
                
                        <div class="form-group validate">
                           
                            <input type="time" name="end_time" class="form-control" id="end_time">
                            <small class="text-red text-muted mySpan"></small>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary  btnUpdate">Update</button>
                            
                        </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}

<script>
    
    

    // raffraichir la page body 
   function getReffreshBody(){
        $.ajax({
            url: $("body").data('url'),
            type: "GET",
            success: function(resp){
                $("body").html(resp);
                // replacer pas la nouvelle page avec les nouvelles modificaions
                $("body").replaceAll("body")

            },
            error: function(resp){
                console.log("something went wrong");
            }
        });
    }
    

    // appel d'une fonction chaque 2 seconde 
    {% comment %} setInterval(function(){
        getReffreshBody()
    }, 2000) {% endcomment %}


    $("#table tbody").on("click", ".link-edit", function(e){
        e.preventDefault();
        var $this = $(this); // this ==> tbody

        // recucpere les valeurs dans HTML 
        let owner = $this.parents(".record").find('td').eq(0).text();
        let task = $this.parents(".record").find('td').eq(1).text();
        let taskDate = $this.data("date");
        let startTime = $this.data("start");
        let endTime = $this.data("end");
        console.log(startTime)
        
        // entrer les donnee dans les input du modal
        $("#formEdit input[name='owner']").val(owner);
        $("#formEdit input[name='name']").val(task);
        $("#formEdit input[name='task_date']").val(taskDate);
        $("#formEdit input[name='start_time']").val(startTime);
        $("#formEdit input[name='end_time']").val(endTime);

        $("#formEdit").attr("action", $this.attr('href')); 

        $("#editModal").modal("show")
        return false;
    });

    $("#formEdit").on("submit", function(e){
        e.preventDefault();
        e.stopPropagation();
        var $this = $(this);
        var valid = true;

        // pour chaque input 
        $('#formEdit input').each(function() {
            let $this = $(this);
            
            // si un input ne contient pas de valeur 
            if(!$this.val()) {
                valid = false;
                $this.parents('.validate').find('.mySpan').text('The '+$this.attr('name').replace(/[\_]+/g, ' ')+' field is required');
            }
        });

        if(valid){
            let data = $this.serialize();
            $.ajax({
                url: $this.attr("action"),
                type: "POST",
                data: data,
                dataType: "json",
                success: function(resp){
                    if(resp.message == "success"){
                        alert("Updated successful");
                        $("#editModal").modal('hide');

                        getReffreshBody()//appel la fonction actualiser
                    }
                    else{
                        alert(resp.message);
                    }
                },
                error: function(resp){
                    console.log("Something went wrong");
                }
            });
        }
        return false;
    });




    $(".link-delete").on("click", function(e){
        e.preventDefault();
        var $this = $(this);
        if(confirm("Sure to delete?")){
            $.ajax({
                url: $this.attr("href"),
                type: "GET",
                dataType: "json",
                success: function(resp){
                    if(resp.message == "success"){
                        $this.parents(".record").fadeOut("slow", function(){
                            $this.parents(".record").remove();
                        });
                    }else{
                        alert(resp.message);
                    }
                }
            });
        }
        return false;
    });


</script>

{% endblock scripts %}